### ISSUE TITLE
Plugin unregistered after updating

### ISSUE THREAD

**Issue by lukecarbis** [hello-wp/hello-charts#141]
After updating from 1.0.0 to 1.0.1, the plugin became unregistered. We should test to make sure that it doesn't happen again when updating to 1.0.2.

**Comment by byronkeet** [comment]
@lukecarbis I have been testing this and had a strange result. On my Mac, the first time I bumped the version, it did unregister my license. However, after re-adding the key, and changing versions many times more, up and down, even up to 1.0.5, the license never unregistered again. I think I ran it like 10 times straight.

Next, I ran a test on my Linux machine. Even on the first attempt on the version bump, it never unregistered the license. Again, after multiple attempts, up and down, the license stayed intact.

So I do recognise that this could be an issue but I have not been able to reproduce the issue. Perhaps we should close this ticket and open it again if we get support issues on it?

**Comment by lukecarbis** [comment]
Sounds good!
